Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: ''
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix: ''
  Charset: utf8
  PaseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30